### ISSUE TITLE
You are banned from the server / Crashes after spawn

### ISSUE THREAD

**Issue by pedropapa** [MishaKonsta/jni#2]
Related to #1 

As soon I tries to join the server I get "You are banned from the server", I tried several servers including the default Russian server in the C++ project. Seems like it's an issue with Raknet authentication packages.

If I compile libsamp.so generated by this project: https://github.com/SA-MP-Mobile/SA-MP-Mobile

It works (I can join the server), currently I'm investigating some differences in Raknet implementation on both projects, but I think @MishaKonsta can do it more quickly to solve the problem.

**Comment by pedropapa** [comment]
Alright, I managed to connect to servers after doing some tweaks on the netgame.cpp file, but the game is crashing once I click "Spawn", stacktrace:

```SIGSEGV | Fault address: 0xFF4801B0
libGTASA base address: 0xC7E86000
register states:
r0: 0xFF480174, r1: 0x5D, r2: 0x3, r3: 0x0
r4: 0xe6b524dc, r5: 0xff4e001b, r6: 0xc69f9000, r7: 0x0
r8: 0xc617f388, r9: 0xe6b523cc, sl: 0x1, fp: 0x896
ip: 0xe6b52d00, sp: 0xc3c9eb98, lr: 0xe6b264b9, pc: 0xe6b26054
backtrace:
1: libGTASA.so + 0x1ECA0054
2: libGTASA.so + 0x1ECA04B9
1: libsamp.so + 0x1EE26054
2: libsamp.so + 0x1EE264B9```

**Comment by sampapk** [comment]
conseguiu arrumar?

**Comment by pedropapa** [comment]
> conseguiu arrumar? (Did you managed to fix it?)

Nope, I can't run the app in a debuggable mode because it crashes soon after SA-MP's splashscreen, so I can't get the memory heap info to analyze the faulty addresses.
